### ISSUE TITLE
Atlant.io giving server error while withdrawing

### ISSUE THREAD

**Issue by vividcode** [AtlantPlatform/atlant-dex#3]
This is SUPER CRITICAL.

It is quite PATHETIC to having to write such request over this place but there is NO CUSTOMER SUPPORT available on the website.

I type my etherdelta address to withdraw my tokens but IT IS NO LONGER ALLOWING to withdraw! All it says is "Server error" - it queues up the transaction and soon cancels it.

If you people are serious about the credibility please FIX THIS PROBLEM ASAP!

There is no single way of transferring purchased ATLs to other wallet!!!

**Comment by prittwitz** [comment]
Im feeling they also have a few other problems. 
Tried to DEPOSIT into YoBit yesterday, deposit obviously just got lost or cashed in. After I can see that the deposit address has successfully received the tokens I cant see anything in YoBit.
YoBit is known as an unserious exchange, but I expect you guys to at least give a customer support or reopen the telegram group you guys closed..

**Comment by varsize** [comment]
Server error issue had previously appeared in case of incorrect 2FA code submission, this had been fixed a while ago.
